---

- name: Dump the ansible environment
  connection: local
  local_action: template src=environment.log.j2 dest={{ inventory_dir }}/environment.log
  sudo: no

- name: ensure common packages are present
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - curl
    - git
    - htop
    - iftop
    - manpages
    - openssl
    - vim
    - wget

- name: ensure the system user is present
  user: name={{ system_user }} shell=/bin/bash

- name: ensure the system user has sudo priveledges
  template: src=sudoers.j2 dest=/etc/sudoers.d/{{ system_user }} owner=root group=root mode=0440

# - name: ensure the bashrc file is present
#   copy: src=bashrc dest=/home/{{ system_user }}/.bashrc mode=0700

- name: ensure the authorized keys are present
  authorized_key: user={{ system_user }} key="{{ lookup('file', item) }}"
  with_items: authorized_keys
