# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.hostname = "photolab"

    config.vm.provider "virtualbox" do |vbx|
        vbx.name = "photolab"
        vbx.memory = 512
        vbx.cpus = 1
    end
end
