---

- name: ensure required system packages are present
  apt: name={{ item }} state=present
  with_items:
    - git
    - python-dev
    - python-pip

- name: enure the required python modules are present
  pip: name={{ item }} state=present
  with_items:
    - uwsgi
    - virtualenv

- name: ensure the application source is present
  git: repo={{ photolab_repo }} dest={{ photolab_app_dir }} version={{ photolab_version }}

- name: ensure the application dependencies are present
  pip: requirements=requirements.txt chdir={{ photolab_app_dir }} virtualenv={{ photolab_virtualenv }}

- name: ensure the local configuration is present
  template: src=local_settings.py.j2 dest={{ photolab_app_dir }}/photolab/local_settings.py

- name: ensure the application state directory is present
  file: path={{ photolab_state_dir }} state=directory owner={{ photolab_user }} group={{ photolab_user }} mode=0775
